### ISSUE TITLE
Error when open

### ISSUE THREAD

**Issue by VladislavAntonyuk** [xamarin/SignaturePad#132]
### Description

System.InvalidCastException
  HResult=0x80004002
  Message=Unable to cast object of type 'SignaturePad.Forms.SignaturePadCanvasRenderer' to type 'Xamarin.Forms.IRegisterable'.
  Source=Xamarin.Forms.Core
  StackTrace:
   at Xamarin.Forms.Internals.Registrar`1.GetHandler(Type type)
   at Xamarin.Forms.Internals.Registrar`1.GetHandlerForObject[TOut](Object obj)
   at Xamarin.Forms.Platform.WPF.Platform.CreateRenderer(VisualElement element)
   at Xamarin.Forms.Platform.WPF.LayoutRenderer.<>c__DisplayClass5_0.<HandleChildAdded>b__0()
   at Xamarin.Forms.Platform.WPF.Helpers.UiHelper.ExecuteInUiThread(Action action)
   at Xamarin.Forms.Platform.WPF.LayoutRenderer.HandleChildAdded(Object sender, ElementEventArgs e)
   at Xamarin.Forms.Platform.WPF.LayoutRenderer.OnElementChanged(ElementChangedEventArgs`1 e)
   at Xamarin.Forms.Platform.WPF.ViewRenderer`2.SetElement(VisualElement element)
   at Xamarin.Forms.Platform.WPF.Platform.CreateRenderer(VisualElement element)
   at Xamarin.Forms.Platform.WPF.LayoutRenderer.<>c__DisplayClass5_0.<HandleChildAdded>b__0()
   at Xamarin.Forms.Platform.WPF.Helpers.UiHelper.ExecuteInUiThread(Action action)
   at Xamarin.Forms.Platform.WPF.LayoutRenderer.HandleChildAdded(Object sender, ElementEventArgs e)
   at Xamarin.Forms.Platform.WPF.LayoutRenderer.OnElementChanged(ElementChangedEventArgs`1 e)
   at Xamarin.Forms.Platform.WPF.ViewRenderer`2.SetElement(VisualElement element)
   at Xamarin.Forms.Platform.WPF.Platform.CreateRenderer(VisualElement element)
   at Xamarin.Forms.Platform.WPF.LayoutRenderer.<>c__DisplayClass5_0.<HandleChildAdded>b__0()
   at Xamarin.Forms.Platform.WPF.Helpers.UiHelper.ExecuteInUiThread(Action action)
   at Xamarin.Forms.Platform.WPF.LayoutRenderer.HandleChildAdded(Object sender, ElementEventArgs e)
   at Xamarin.Forms.Platform.WPF.LayoutRenderer.OnElementChanged(ElementChangedEventArgs`1 e)
   at Xamarin.Forms.Platform.WPF.ViewRenderer`2.SetElement(VisualElement element)
   at Xamarin.Forms.Platform.WPF.Platform.CreateRenderer(VisualElement element)
   at Xamarin.Forms.Platform.WPF.Platform.GetOrCreateRenderer(VisualElement element)
   at Xamarin.Forms.Platform.WPF.PageRenderer.UpdateContent()
   at Xamarin.Forms.Platform.WPF.PageRenderer.OnElementChanged(ElementChangedEventArgs`1 e)
   at Xamarin.Forms.Platform.WPF.ViewRenderer`2.SetElement(VisualElement element)
   at Xamarin.Forms.Platform.WPF.Platform.CreateRenderer(VisualElement element)
   at Xamarin.Forms.Platform.WPF.Platform.GetOrCreateRenderer(VisualElement element)
   at Xamarin.Forms.Platform.WPF.FormsContentLoader.CreateOrResizeContent(FrameworkElement parent, VisualElement visualElement)
   at Xamarin.Forms.Platform.WPF.FormsContentLoader.OnSizeContentChanged(FrameworkElement parent, Object page)
   at WpfLightToolkit.Controls.LightContentControl.LightContentControl_SizeChanged(Object sender, SizeChangedEventArgs e)
   at System.Windows.SizeChangedEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   at System.Windows.FrameworkElement.OnRenderSizeChanged(SizeChangedInfo sizeInfo)
   at System.Windows.ContextLayoutManager.fireSizeChangedEvents()
   at System.Windows.ContextLayoutManager.UpdateLayout()
   at System.Windows.ContextLayoutManager.UpdateLayoutCallback(Object arg)
   at System.Windows.Media.MediaContext.InvokeOnRenderCallback.DoWork()
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at System.Windows.Application.Run()
   at WPF.App.Main()

### Basic Information

- Version with issue:  
- Last known good version:  
- IDE:  
- Platform Target Frameworks: 
  - Android:  
  - iOS:  
  - UWP:   
  - Xamarin.Forms:  
- Target Devices:
  -

**Comment by VladislavAntonyuk** [comment]
I think if Microsoft support wpf in xamarin if can became more popular because of cross platform desktop app. I think the problem is that some changes in renderer in version 3.0 and your implementation on 2.5 is not fully implement it. Could you please update signature pad to xamarin 3.0 version

**Comment by mattleibow** [comment]
I will be doing that soon. I was just getting the repo ready and updating to the new project format.

**Comment by fjaviergallucci** [comment]
Hi guys,

Good job with the library. I'm very exited to use this library in my project, but I'm having some troubles trying to using it. I use the same code from your sample project to Xamarin Forms, but I'm getting the same error loading the view.

I tried Signature Pad 2.3 with Xamarin.Forms 3.0, 2.4 and 2.5 and it didn't work. I also tried the 3.0 preview with Xamarin.Forms 3.0, 2.5 and 2.4 but nothing, same result, when the view is loading I'm getting the error: 

System.InvalidCastException: Specified cast is not valid.

The target of my Xamarin Forms project is NF 4.5, Net Core 1. And for the Android project is 8.1.

Hope you can help me.

Thanks.

**Comment by fjaviergallucci** [comment]
Ok, good news. I was finally able to make it work, but I had to downgraded Xamarin.Forms to 2.3 and use Signature Pad 2.2.

Do you have plans to upgrade to Xamarin 2.5 or even 3?

Thanks for your work guys.

**Comment by adampenn** [comment]
@mattleibow I am having this same issue now, I just inherited a Xamarin app from another developer and am not super familiar so I apologize ahead of time if my questions are obvious.

1. I see that you said in the comment above that you would be updating to 3.0 soon; has this been done?

2. Out application uses the signature pad and our primary devices being used are windows laptops. You said up above that WPF would require a backing implementation is that something I could extend on myside and make it work? (possible creating a pr for you to add support)

Thank you for your time and please let me know if any of my questions dont make sense.

Side note we are using version 3.0 of signature pad.

**Comment by VladislavAntonyuk** [comment]
@adampenn https://github.com/xamarin/SignaturePad/pull/138
