### ISSUE TITLE
Crash on UWP

### ISSUE THREAD

**Issue by Dabbel** [xamarin/SignaturePad#95]
Hi, when i call GetImageStreamAsync(SignatureImageFormat.Jpeg, Color.FromHex("#999999"), Color.White) the app crashs and i get this stacktrace

`
System.ArgumentException: Value does not fall within the expected range.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Xamarin.Controls.SignaturePadCanvasView.<GetImageStreamInternal>d__13.MoveNext()
`

**Comment by mattleibow** [comment]
Thanks for reporting this, I will investigate.

**Comment by mattleibow** [comment]
I was not able to reproduce this.

Do you have any more information? What version of SignaturePad?

**Comment by Dabbel** [comment]
Have the problem with version 2.3.0. Is it possible that you provide the pdb files, maybe the better stacktrace helps.
